import type { LucideIcon } from "lucide-react"
import { Bot, CalendarDays, BarChart3, Wallet, MessageCircle, Package, Receipt, DollarSign, Users, AlertTriangle, ShieldCheck, TrendingUp, Globe, Target, Cake } from "lucide-react"

export interface Feature {
  id: string
  icon: LucideIcon
  title: string
  description: string
  tagline: string
  details: string[]
  result: string
}

export const featuresData: Feature[] = [
  {
    id: "ia-atendente",
    icon: Bot,
    title: "IA Atendente WhatsApp",
    description: "Responde 24/7 automaticamente",
    tagline: "O diferencial que seu concorrente não tem!",
    details: [
      "Responde sobre serviços, preços e horários",
      "Envia link direto para o portal de agendamento",
      "Tira dúvidas enquanto você trabalha",
      "Nunca deixa cliente sem resposta",
      "Você vê quem leu as mensagens (recurso nativo do WhatsApp)",
    ],
    result: "Seus profissionais focam no atendimento presencial enquanto a IA cuida do WhatsApp. É como ter uma secretária que nunca tira folga, por uma fração do custo!",
  },
  {
    id: "agenda-inteligente",
    icon: CalendarDays,
    title: "Agenda Inteligente",
    description: "Agendamento online simplificado",
    tagline: "Controle total sobre os agendamentos do seu estabelecimento",
    details: [
      "Agendamento online 24 horas por dia, 7 dias por semana pelo portal do cliente",
      "Manual de agendamento pela recepção ou profissional",
      "Múltiplos serviços por agendamento",
      "Política de antecedência: Configure quantas horas/dias antes aceitar agendamentos",
      "Jornada personalizada por profissional e dia da semana",
      "Jornada estendida por período (ex: dezembro até mais tarde)",
      "Prevenção automática de conflitos de horários",
      "Agendamento presencial (walk-in) para clientes sem hora marcada",
    ],
    result: "Sua agenda organizada automaticamente, sem conflitos, respeitando as regras do SEU negócio.",
  },
  {
    id: "performance",
    icon: BarChart3,
    title: "Performance de Profissionais",
    description: "Métricas dos profissionais",
    tagline: "Saiba EXATAMENTE o desempenho de cada profissional",
    details: [
      "Quantidade de atendimentos realizados por período",
      "Lucro gerado por cada profissional (R$ exato)",
      "Material consumido (controle de produtos usados)",
      "Comissões a pagar (automático)",
      "Receita por dia/semana/mês por profissional",
      "Comparativo de desempenho entre profissionais",
      "Serviços mais realizados por cada um",
    ],
    result: "Decisões baseadas em dados reais. Identifique talentos, otimize escalas e recompense quem mais produz.",
  },
  {
    id: "gestao-financeira",
    icon: Wallet,
    title: "Gestão Financeira Completa",
    description: "Controle total de receitas",
    tagline: "Tenha o controle total das finanças do seu negócio",
    details: [
      "Controle de caixa completo",
      "Contas a pagar e receber organizadas",
      "Receita bruta (serviços + produtos)",
      "Lucro líquido (receita - comissões - despesas)",
      "Despesas mensais",
      "Folha salarial detalhada por profissional",
      "Relatórios comparativos mensais",
      "Registro de pagamentos (dinheiro, cartão, Pix, etc)",
    ],
    result: "Visão 360° da saúde financeira do seu negócio. Saiba exatamente quanto está ganhando de verdade.",
  },
  {
    id: "comunicacao",
    icon: MessageCircle,
    title: "Comunicação Automatizada",
    description: "Lembretes automatizados",
    tagline: "Mantenha seus clientes sempre informados, automaticamente",
    details: [
      "Lembretes de horário automáticos via WhatsApp",
      "Mensagens de retorno para clientes inativos",
      "Envio de promoções e eventos para grupos específicos",
      "Aniversariantes do dia com mensagens personalizadas",
      "Avisos semanais no portal do cliente",
      "Confirmações automáticas de agendamento",
    ],
    result: "Reduza no-shows, aumente a frequência de retorno e mantenha o relacionamento ativo com seus clientes sem esforço manual.",
  },
  {
    id: "gestao-estoque",
    icon: Package,
    title: "Gestão de Estoque",
    description: "Controle de produtos",
    tagline: "Controle total dos seus produtos",
    details: [
      "Cadastro de produtos com preço de venda e custo",
      "Controle de estoque atual e mínimo",
      "Entrada de produtos (compras/reposição)",
      "Consumo interno por profissional",
      "Venda de produtos direto na comanda",
      "Alerta de estoque mínimo automático",
      "Histórico de movimentações completo",
      "Cálculo automático de lucro por produto",
      "Pacotes de produtos com preço promocional",
    ],
    result: "Nunca mais fique sem produto essencial. Saiba exatamente o lucro de cada venda e quanto cada profissional consome.",
  },
  {
    id: "comandas-vendas",
    icon: Receipt,
    title: "Comandas e Vendas",
    description: "PDV integrado ao sistema",
    tagline: "Controle total de consumo e vendas",
    details: [
      "Comanda automática em cada agendamento",
      "Comanda avulsa para clientes sem agendamento",
      "Adicionar serviços extras na comanda",
      "Adicionar produtos consumidos/vendidos",
      "Aplicar descontos personalizados",
      "Várias formas de pagamento (dinheiro, Pix, cartão)",
      "Cálculo automático de total e troco",
      "Atualização automática de estoque ao finalizar",
    ],
    result: "Zero erros de cobrança. Tudo registrado e organizado automaticamente.",
  },
  {
    id: "comissoes",
    icon: DollarSign,
    title: "Sistema de Comissões",
    description: "Cálculo automático",
    tagline: "Cálculo automático e transparente",
    details: [
      "Comissão por serviço realizado",
      "Comissão por produto vendido",
      "Percentual ou valor fixo por item",
      "Cálculo automático (trigger no banco de dados)",
      "Relatório de comissões a pagar por período",
      "Histórico de pagamentos realizados",
      "Transparência total com o profissional",
      "Controle de consumo dos profissionais",
    ],
    result: "Acabe com brigas e discussões. Relatório claro e automático de quanto pagar para cada profissional.",
  },
  {
    id: "gestao-clientes",
    icon: Users,
    title: "Gestão de Clientes",
    description: "CRM completo integrado",
    tagline: "Conheça profundamente seus clientes",
    details: [
      "Cadastro completo (nome, telefone, e-mail, nascimento)",
      "Histórico de atendimentos completo",
      "Última visita atualizada automaticamente",
      "Serviços preferidos registrados",
      "Observações personalizadas por cliente",
      "Vinculação com usuário do portal",
      "Busca e filtros avançados",
    ],
    result: "Atendimento personalizado. Saiba quem é seu cliente fiel e quem está sumido.",
  },
  {
    id: "cancelamentos",
    icon: AlertTriangle,
    title: "Controle de Cancelamentos",
    description: "Controle de no-shows",
    tagline: "Identifique clientes problemáticos",
    details: [
      "Histórico completo de cancelamentos por cliente",
      "Contador de quantas vezes cancelou",
      "Visualização fácil de 'clientes problema'",
      "Tome decisões baseadas em dados (ex: bloqueio após 3 cancelamentos)",
      "Proteja sua agenda de cancelamentos de última hora",
    ],
    result: "Reduza prejuízos com horários vagos. Identifique quem realmente merece prioridade na sua agenda.",
  },
  {
    id: "niveis-acesso",
    icon: ShieldCheck,
    title: "6 Níveis de Acesso",
    description: "Permissões personalizadas",
    tagline: "Controle granular de permissões",
    details: [
      "Administrador - Acesso total ao sistema",
      "Gerente - Operações do dia-a-dia e relatórios",
      "Recepcionista - Agendamentos, clientes e vendas",
      "Profissional - Apenas seus agendamentos e comissões",
      "Auxiliar - Permissões personalizadas",
      "Cliente - Portal de agendamento",
    ],
    result: "Segurança e organização. Profissional não vê dados financeiros. Recepcionista não mexe em configurações.",
  },

  {
    id: "relatorios",
    icon: TrendingUp,
    title: "Relatórios Gerenciais",
    description: "Dados gerenciais completos",
    tagline: "Transforme dados em decisões",
    details: [
      "Agendamentos por dia da semana - Identifique dias fracos",
      "Agendamentos por horário - Otimize escalas",
      "Desempenho por profissional - Compare produtividade",
      "Produtos mais vendidos - Foque no que dá lucro",
      "Relatórios comparativos - Compare mês a mês",
      "Análise de lucro - Veja o que realmente dá dinheiro",
      "Comissões detalhadas - Transparência total",
    ],
    result: "Decisões baseadas em dados reais, não em 'achismos'. Identifique oportunidades e problemas rapidamente.",
  },
  {
    id: "portal-cliente",
    icon: Globe,
    title: "Portal do Cliente",
    description: "Autoatendimento online",
    tagline: "Seu estabelecimento online 24 horas por dia, 7 dias por semana",
    details: [
      "Link único do seu estabelecimento",
      "Autocadastro de novos clientes",
      "Agendamento online com horários disponíveis",
      "Seleção de profissional preferido",
      "Múltiplos serviços por vez",
      "Consulta de agendamentos próprios",
      "Cancelamento de agendamentos futuros",
      "Avisos semanais personalizados",
      "Interface responsiva (celular, tablet, desktop)",
    ],
    result: "Clientes agendam sozinhos a qualquer hora. Você ganha tempo e profissionalismo.",
  },
  {
    id: "multi-nicho",
    icon: Target,
    title: "Multi-Nicho (Universal)",
    description: "Adaptável ao seu negócio",
    tagline: "Um sistema para QUALQUER tipo de negócio com agendamentos",
    details: [
      "Salão de Beleza - Manicure, cabeleireiro, maquiagem",
      "Barbearia - Corte, barba, tratamentos",
      "Clínica - Médicos, dentistas, terapeutas",
      "Spa - Massagens, estética, tratamentos",
      "Consultório - Psicólogos, nutricionistas",
      "Pet Shop - Banho, tosa, veterinário",
      "Estética - Procedimentos, depilação",
      "E muito mais!",
      "Nomenclatura personalizável: Configure como 'terapeuta', 'médico', 'esteticista' ou o que precisar!",
    ],
    result: "Um sistema que CRESCE com você. Mudou de nicho? Não precisa trocar de sistema!",
  },
  {
    id: "aniversariantes",
    icon: Cake,
    title: "Aniversariantes",
    description: "Fidelização automática",
    tagline: "Nunca esqueça uma data especial",
    details: [
      "Lista de aniversariantes do dia",
      "Notificação automática para você",
      "Envio automático de mensagem de parabéns",
      "Oportunidade de promoção especial de aniversário",
      "Mensagens personalizadas por WhatsApp",
    ],
    result: "Fidelização através do carinho. Cliente fica feliz por ser lembrado e você ganha pontos de relacionamento!",
  },
]
